#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
#ifndef KASHIERPAYMENTSDK_SWIFT_H
#define KASHIERPAYMENTSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="KashierPaymentSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UITextField;
@class NSCoder;
@class NSString;
@class NSBundle;

SWIFT_CLASS("_TtC17KashierPaymentSDK21AddCardViewController")
@interface AddCardViewController : UIViewController <UITextFieldDelegate>
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (void)viewDidLoad;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class ErrorData;

SWIFT_CLASS("_TtC17KashierPaymentSDK4Card")
@interface Card : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull cardHolderName;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardCcv;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardExpiryMonth;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardExpiryYear;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardExpiryDate;
- (nonnull instancetype)initWithCardHolderName:(NSString * _Nonnull)cardHolderName cardNumber:(NSString * _Nonnull)cardNumber cardCcv:(NSString * _Nonnull)cardCcv cardExpiryMonth:(NSString * _Nonnull)cardExpiryMonth cardExpiryYear:(NSString * _Nonnull)cardExpiryYear OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCardHolderName:(NSString * _Nonnull)cardHolderName cardNumber:(NSString * _Nonnull)cardNumber cardCcv:(NSString * _Nonnull)cardCcv cardExpiryDate:(NSString * _Nonnull)cardExpiryDate OBJC_DESIGNATED_INITIALIZER;
+ (ErrorData * _Nonnull)getCardParsingError SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK12Card3DSecure")
@interface Card3DSecure : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable acsURL;
@property (nonatomic, readonly, copy) NSString * _Nullable paReq;
@property (nonatomic, readonly, copy) NSString * _Nullable processACSRedirectURL;
@property (nonatomic, readonly, copy) NSString * _Nullable requestType;
@property (nonatomic, readonly, copy) NSString * _Nullable the3DSecureID;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class CardInfo;
@class Transaction;

SWIFT_CLASS("_TtC17KashierPaymentSDK8CardCard")
@interface CardCard : NSObject
@property (nonatomic, readonly, strong) Card3DSecure * _Nullable the3DSecure;
@property (nonatomic, readonly, strong) CardInfo * _Nullable cardInfo;
@property (nonatomic, readonly, strong) Transaction * _Nullable transaction;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK8CardInfo")
@interface CardInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable cardHolderName;
@property (nonatomic, readonly, copy) NSString * _Nullable expiryMonth;
@property (nonatomic, readonly, copy) NSString * _Nullable expiryYear;
@property (nonatomic, readonly, copy) NSString * _Nullable cardHash;
@property (nonatomic, readonly, copy) NSString * _Nullable cardDataToken;
@property (nonatomic, readonly, copy) NSString * _Nullable cardBrand;
@property (nonatomic, readonly, copy) NSString * _Nullable maskedCard;
@property (nonatomic, readonly, copy) NSString * _Nullable ccvToken;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSNumber;
@class ValidationResult;

SWIFT_CLASS("_TtC17KashierPaymentSDK20CardValidationResult")
@interface CardValidationResult : NSObject
@property (nonatomic, readonly) BOOL isCardValid;
@property (nonatomic, readonly, copy) NSArray<ValidationResult *> * _Nonnull validationErrors;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK23CardsListViewController")
@interface CardsListViewController : UIViewController
- (void)viewDidLoad;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK18Connected_Accounts")
@interface Connected_Accounts : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull mid;
- (nonnull instancetype)initWithMid:(NSString * _Nonnull)mid OBJC_DESIGNATED_INITIALIZER;
- (NSDictionary<NSString *, NSString *> * _Nonnull)toDictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ERROR_TYPE, open) {
  ERROR_TYPENO_VALUE = 0,
  ERROR_TYPEINITIALIZATION = 1,
  ERROR_TYPEVALIDATION = 2,
  ERROR_TYPEDATA = 3,
  ERROR_TYPEEXCEPTION = 4,
  ERROR_TYPENETWORK_ERROR = 5,
  ERROR_TYPENETWORK_NO_INTERNET = 6,
  ERROR_TYPENETWORK_TIMEOUT = 7,
  ERROR_TYPENETWORK_UNAUTHENTICATED = 8,
  ERROR_TYPENETWORK_CLIENT_ERROR = 9,
  ERROR_TYPENETWORK_SERVER_ERROR = 10,
  ERROR_TYPENETWORK_UNEXPECTED_ERROR = 11,
  ERROR_TYPEJSON_PARSING_ERROR = 12,
};

enum KASHIER_RESPONSE_STATUS : NSInteger;
@class GenericResponse;

SWIFT_CLASS("_TtC17KashierPaymentSDK9ErrorData")
@interface ErrorData : NSObject
@property (nonatomic, readonly) enum ERROR_TYPE errorType;
@property (nonatomic, readonly) enum KASHIER_RESPONSE_STATUS responseStatus;
@property (nonatomic, readonly, copy) NSString * _Nonnull errorMessage;
@property (nonatomic, readonly, copy) NSArray<ValidationResult *> * _Nonnull validationErrors;
@property (nonatomic, readonly, strong) GenericResponse * _Nullable Response;
@property (nonatomic, readonly, copy) NSString * _Nonnull exceptionErrorMessage;
@property (nonatomic, readonly, copy) NSString * _Nonnull networkErrorCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)getErrorMessage SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getValidationErrorsMessage SWIFT_WARN_UNUSED_RESULT;
@end

@class P_Body;
@class P_Response;
@class P_Messages;
@class P_Error;

SWIFT_CLASS("_TtC17KashierPaymentSDK15GenericResponse")
@interface GenericResponse : NSObject
@property (nonatomic, strong) P_Body * _Nullable body;
@property (nonatomic, strong) P_Response * _Nullable responseModel;
@property (nonatomic, strong) P_Messages * _Nullable messages;
@property (nonatomic, strong) P_Error * _Nullable error;
@property (nonatomic, copy) NSString * _Nonnull status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, KASHIER_DISPLAY_LANG, open) {
  KASHIER_DISPLAY_LANGAR = 0,
  KASHIER_DISPLAY_LANGEN = 1,
};

typedef SWIFT_ENUM(NSInteger, KASHIER_RESPONSE_STATUS, open) {
  KASHIER_RESPONSE_STATUSNO_VALUE = 0,
  KASHIER_RESPONSE_STATUSUNKNOWN = 1,
  KASHIER_RESPONSE_STATUSSUCCESS = 2,
  KASHIER_RESPONSE_STATUSFAILURE = 3,
  KASHIER_RESPONSE_STATUSINVALID_REQUEST = 4,
  KASHIER_RESPONSE_STATUSPENDING = 5,
  KASHIER_RESPONSE_STATUSPENDING_ACTION = 6,
};

typedef SWIFT_ENUM(NSInteger, KASHIER_SDK_MODE, open) {
  KASHIER_SDK_MODEDEVELOPMENT = 0,
  KASHIER_SDK_MODEPRODUCTION = 1,
};

typedef SWIFT_ENUM(NSInteger, KASHIER_TOKEN_VALIDITY, open) {
  KASHIER_TOKEN_VALIDITYTEMPORARY = 0,
  KASHIER_TOKEN_VALIDITYPERMANENT = 1,
};

@protocol KashierTheme;
@class PaymentCallback;
@class TokensListCallback;
@class TokenizationCallback;
@class OrderDetailsCallback;

SWIFT_CLASS("_TtC17KashierPaymentSDK7Kashier")
@interface Kashier : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) enum KASHIER_SDK_MODE sdkMode;)
+ (enum KASHIER_SDK_MODE)sdkMode SWIFT_WARN_UNUSED_RESULT;
+ (void)setKashierTheme:(id <KashierTheme> _Nonnull)theme;
+ (void)setConnectedAccount:(Connected_Accounts * _Nonnull)connectedAccountData;
+ (void)initializeObjCWithMerchantId:(NSString * _Nonnull)merchantId apiKey:(NSString * _Nonnull)apiKey sdkMode:(enum KASHIER_SDK_MODE)sdkMode;
+ (void)initializeObjCWithMerchantId:(NSString * _Nonnull)merchantId apiKey:(NSString * _Nonnull)apiKey secretKey:(NSString * _Nonnull)secretKey sdkMode:(enum KASHIER_SDK_MODE)sdkMode currency:(NSString * _Nonnull)currency;
+ (void)initializeObjCWithMerchantId:(NSString * _Nonnull)merchantId apiKey:(NSString * _Nonnull)apiKey sdkMode:(enum KASHIER_SDK_MODE)sdkMode secretKey:(NSString * _Nonnull)secretKey currency:(NSString * _Nonnull)currency displayLang:(enum KASHIER_DISPLAY_LANG)displayLang;
+ (void)payWithPermTokenWithShopperReference:(NSString * _Nonnull)shopperReference orderId:(NSString * _Nonnull)orderId amount:(NSString * _Nonnull)amount cardToken:(NSString * _Nonnull)cardToken paymentCallback:(PaymentCallback * _Nonnull)paymentCallback;
+ (void)payWithTempTokenWithShopperReference:(NSString * _Nonnull)shopperReference orderId:(NSString * _Nonnull)orderId amount:(NSString * _Nonnull)amount cardToken:(NSString * _Nonnull)cardToken cvvToken:(NSString * _Nonnull)cvvToken paymentCallback:(PaymentCallback * _Nonnull)paymentCallback;
+ (void)payWithCardWithCardData:(Card * _Nonnull)cardData orderId:(NSString * _Nonnull)orderId amount:(NSString * _Nonnull)amount shopperReference:(NSString * _Nonnull)shopperReference shouldSaveCard:(BOOL)shouldSaveCard paymentCallback:(PaymentCallback * _Nonnull)paymentCallback;
+ (void)listShopperCardsWithShopperReference:(NSString * _Nonnull)shopperReference userCallBack:(TokensListCallback * _Nonnull)userCallBack;
+ (void)saveShopperCardWithCardData:(Card * _Nonnull)cardData shopperReference:(NSString * _Nonnull)shopperReference tokenValidity:(enum KASHIER_TOKEN_VALIDITY)tokenValidity tokenizationCallback:(TokenizationCallback * _Nonnull)tokenizationCallback;
+ (void)payUsingPaymentFormWithOrderId:(NSString * _Nonnull)orderId amount:(NSString * _Nonnull)amount shopperReference:(NSString * _Nonnull)shopperReference paymentCallback:(PaymentCallback * _Nonnull)paymentCallback customXibFile:(NSString * _Nullable)customXibFile;
+ (void)listShopperCardsUIWithShopperReference:(NSString * _Nonnull)shopperReference;
+ (void)getOrderDetailsWithOrderId:(NSString * _Nonnull)orderId shopperReference:(NSString * _Nullable)shopperReference orderDetailsCallback:(OrderDetailsCallback * _Nonnull)orderDetailsCallback;
+ (NSString * _Nonnull)getString SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getStringWithParamWithStr:(NSString * _Nonnull)myStr SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;

SWIFT_PROTOCOL("_TtP17KashierPaymentSDK12KashierTheme_")
@protocol KashierTheme
@property (nonatomic, strong) UIColor * _Nonnull primaryColor;
@property (nonatomic, strong) UIColor * _Nonnull primaryColorVariant;
@property (nonatomic, strong) UIColor * _Nonnull secondaryColor;
/// Can be used to extend the functionality of the theme, by applying more colors to some components
- (void)extend;
@end

@class UIApplication;

SWIFT_CLASS("_TtC17KashierPaymentSDK18KashierThemeHelper")
@interface KashierThemeHelper : NSObject
+ (void)applyThemeFor:(UIApplication * _Nonnull)application kashierTheme:(id <KashierTheme> _Nonnull)kashierTheme;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK19KashierThemedButton")
@interface KashierThemedButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK18KashierUITextField")
@interface KashierUITextField : UITextField
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC17KashierPaymentSDK8Merchant")
@interface Merchant : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable merchantRedirectURL;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC17KashierPaymentSDK5Order")
@interface Order : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class OrderDetailsResponse;

SWIFT_CLASS("_TtC17KashierPaymentSDK12OrderDetails")
@interface OrderDetails : GenericResponse
@property (nonatomic, readonly, strong) OrderDetailsResponse * _Nullable orderDetailsResponse;
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK20OrderDetailsCallback")
@interface OrderDetailsCallback : NSObject
@property (nonatomic, copy) void (^ _Nonnull onResponse)(OrderDetails * _Nonnull);
- (nonnull instancetype)initOnResponse:(void (^ _Nonnull)(OrderDetails * _Nonnull))onResponse onFailure:(void (^ _Nonnull)(ErrorData * _Nonnull))onFailure OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) void (^ _Nonnull onFailure)(ErrorData * _Nonnull);
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class P_Message;
@class P_Card;

SWIFT_CLASS("_TtC17KashierPaymentSDK10P_Response")
@interface P_Response : NSObject
@property (nonatomic, readonly, strong) P_Messages * _Nullable messages;
@property (nonatomic, readonly, copy) NSString * _Nullable status;
@property (nonatomic, readonly, strong) P_Message * _Nullable message;
@property (nonatomic, readonly, strong) P_Card * _Nullable cardModel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class OrderDetailsSourceOfFunds;
@class OrderDetails_merchantDetails;
@class OrderDetails_order;
@class OrderDetails_transaction;

SWIFT_CLASS("_TtC17KashierPaymentSDK20OrderDetailsResponse")
@interface OrderDetailsResponse : P_Response
@property (nonatomic, readonly, copy) NSString * _Nullable _id;
@property (nonatomic, readonly, copy) NSString * _Nullable merchantId;
@property (nonatomic, readonly, copy) NSString * _Nullable orderId;
@property (nonatomic, readonly, copy) NSString * _Nullable merchantOrderId;
@property (nonatomic, readonly, copy) NSString * _Nullable totalAuthorizedAmount;
@property (nonatomic, readonly, copy) NSString * _Nullable method;
@property (nonatomic, readonly, copy) NSString * _Nullable apiKeyId;
@property (nonatomic, readonly, copy) NSString * _Nullable apiServiceName;
@property (nonatomic, readonly, copy) NSString * _Nullable paymentOrigin;
@property (nonatomic, readonly, copy) NSString * _Nullable paymentChannel;
@property (nonatomic, readonly, copy) NSString * _Nullable provider;
@property (nonatomic, readonly, copy) NSString * _Nullable lastModifiedDate;
@property (nonatomic, readonly, copy) NSString * _Nullable date;
@property (nonatomic, readonly, strong) OrderDetailsSourceOfFunds * _Nullable sourceOfFunds;
@property (nonatomic, readonly, strong) OrderDetails_merchantDetails * _Nullable merchantDetails;
@property (nonatomic, readonly, strong) OrderDetails_order * _Nullable order;
@property (nonatomic, readonly, copy) NSArray<OrderDetails_transaction *> * _Nullable transactions;
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK25OrderDetailsSourceOfFunds")
@interface OrderDetailsSourceOfFunds : NSObject
@property (nonatomic, readonly, strong) CardInfo * _Nullable cardInfo;
@property (nonatomic, readonly, strong) Card3DSecure * _Nullable threeDSecure;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK28OrderDetails_merchantDetails")
@interface OrderDetails_merchantDetails : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable storeName;
@property (nonatomic, readonly, copy) NSString * _Nullable merchantId;
@property (nonatomic, readonly, copy) NSString * _Nullable businessIndustry;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK18OrderDetails_order")
@interface OrderDetails_order : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable amount;
@property (nonatomic, readonly, copy) NSString * _Nullable currency;
@property (nonatomic, readonly, copy) NSString * _Nullable callbackURL;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK24OrderDetails_transaction")
@interface OrderDetails_transaction : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable currency;
@property (nonatomic, readonly, copy) NSString * _Nullable status;
@property (nonatomic, readonly, copy) NSString * _Nullable transactionId;
@property (nonatomic, readonly, copy) NSString * _Nullable operation;
@property (nonatomic, readonly, copy) NSString * _Nullable _id;
@property (nonatomic, readonly, copy) NSString * _Nullable requestDate;
@property (nonatomic, readonly, copy) NSString * _Nullable responseDate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK6P_Body")
@interface P_Body : NSObject
@property (nonatomic, readonly, strong) P_Messages * _Nullable messages;
@property (nonatomic, readonly, copy) NSString * _Nullable status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK6P_Card")
@interface P_Card : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable result;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK7P_Error")
@interface P_Error : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable cause;
@property (nonatomic, readonly, copy) NSString * _Nullable explanation;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK9P_Message")
@interface P_Message : NSObject
@property (nonatomic, readonly, strong) P_Messages * _Nullable messages;
@property (nonatomic, readonly, copy) NSString * _Nullable status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK10P_Messages")
@interface P_Messages : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable en;
@property (nonatomic, readonly, copy) NSString * _Nullable ar;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK10P_Platform")
@interface P_Platform : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable mid;
@property (nonatomic, readonly, copy) NSString * _Nullable storeName;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



IB_DESIGNABLE
SWIFT_CLASS("_TtC17KashierPaymentSDK12PaddingLabel")
@interface PaddingLabel : UILabel
- (void)drawTextInRect:(CGRect)rect;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class PaymentResponse;

SWIFT_CLASS("_TtC17KashierPaymentSDK7Payment")
@interface Payment : GenericResponse
@property (nonatomic, readonly, strong) PaymentResponse * _Nullable response;
- (Card3DSecure * _Nullable)get3DSData SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK15PaymentCallback")
@interface PaymentCallback : NSObject
@property (nonatomic, copy) void (^ _Nonnull onResponse)(Payment * _Nonnull);
- (nonnull instancetype)initOnResponse:(void (^ _Nonnull)(Payment * _Nonnull))onResponse onFailure:(void (^ _Nonnull)(ErrorData * _Nonnull))onFailure OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) void (^ _Nonnull onFailure)(ErrorData * _Nonnull);
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK25PaymentFormViewController")
@interface PaymentFormViewController : UIViewController
- (void)viewDidLoad;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class ResponseCard;
@class SourceOfFunds;

SWIFT_CLASS("_TtC17KashierPaymentSDK15PaymentResponse")
@interface PaymentResponse : P_Response
@property (nonatomic, readonly, copy) NSString * _Nullable orderReference;
@property (nonatomic, readonly, copy) NSString * _Nullable orderID;
@property (nonatomic, readonly, copy) NSString * _Nullable transactionID;
@property (nonatomic, readonly, copy) NSString * _Nullable merchantOrderID;
@property (nonatomic, readonly, copy) NSString * _Nullable creationDate;
@property (nonatomic, readonly, copy) NSString * _Nullable providerType;
@property (nonatomic, readonly, copy) NSString * _Nullable method;
@property (nonatomic, readonly, copy) NSString * _Nullable apiKeyID;
@property (nonatomic, readonly, copy) NSString * _Nullable refID;
@property (nonatomic, readonly, copy) NSString * _Nullable merchantID;
@property (nonatomic, readonly, strong) ResponseCard * _Nullable card;
@property (nonatomic, readonly, strong) SourceOfFunds * _Nullable sourceOfFunds;
@property (nonatomic, readonly, strong) P_Error * _Nullable error;
@property (nonatomic, readonly, strong) P_Platform * _Nullable platform;
@end

@class ProvidedCard;

SWIFT_CLASS("_TtC17KashierPaymentSDK8Provided")
@interface Provided : NSObject
@property (nonatomic, readonly, strong) ProvidedCard * _Nullable card;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK12ProvidedCard")
@interface ProvidedCard : NSObject
@property (nonatomic, readonly, strong) CardCard * _Nullable card;
@property (nonatomic, readonly, strong) CardInfo * _Nullable cardInfo;
@property (nonatomic, readonly, strong) Card3DSecure * _Nullable the3DSecure;
@property (nonatomic, readonly, strong) Transaction * _Nullable transaction;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK8Response")
@interface Response : NSObject
@property (nonatomic, readonly, strong) SourceOfFunds * _Nullable sourceOfFunds;
@property (nonatomic, readonly, copy) NSString * _Nullable orderReference;
@property (nonatomic, readonly, copy) NSString * _Nullable orderID;
@property (nonatomic, readonly, copy) NSString * _Nullable transactionID;
@property (nonatomic, readonly, copy) NSString * _Nullable merchantOrderID;
@property (nonatomic, readonly, copy) NSString * _Nullable creationDate;
@property (nonatomic, readonly, copy) NSString * _Nullable providerType;
@property (nonatomic, readonly, copy) NSString * _Nullable method;
@property (nonatomic, readonly, copy) NSString * _Nullable apiKeyID;
@property (nonatomic, readonly, copy) NSString * _Nullable refID;
@property (nonatomic, readonly, copy) NSString * _Nullable merchantID;
@property (nonatomic, readonly, strong) ResponseCard * _Nullable card;
@property (nonatomic, readonly, strong) P_Platform * _Nullable platform;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK12ResponseCard")
@interface ResponseCard : NSObject
@property (nonatomic, readonly, strong) CardInfo * _Nullable cardInfo;
@property (nonatomic, readonly, strong) Order * _Nullable order;
@property (nonatomic, readonly) double amount;
@property (nonatomic, readonly, copy) NSString * _Nullable currency;
@property (nonatomic, readonly, copy) NSString * _Nullable result;
@property (nonatomic, readonly, strong) Merchant * _Nullable merchant;
@property (nonatomic, readonly, strong) Card3DSecure * _Nullable card3DSecure;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK13SourceOfFunds")
@interface SourceOfFunds : NSObject
@property (nonatomic, readonly, strong) Provided * _Nullable provided;
@property (nonatomic, readonly, copy) NSString * _Nullable type;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIImage;

SWIFT_CLASS("_TtC17KashierPaymentSDK5Token")
@interface Token : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable cardExpiryYear;
@property (nonatomic, readonly, copy) NSString * _Nullable cardExpiryMonth;
@property (nonatomic, readonly, copy) NSString * _Nullable cardNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable creationDate;
@property (nonatomic, readonly, copy) NSString * _Nullable token;
@property (nonatomic, readonly, copy) NSString * _Nullable shopperReference;
@property (nonatomic, readonly, copy) NSString * _Nullable merchantID;
@property (nonatomic, readonly, copy) NSString * _Nullable cardType;
@property (nonatomic, readonly, strong) UIImage * _Nullable cardImage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TokenizationBodyResponse;

SWIFT_CLASS("_TtC17KashierPaymentSDK16TokenizationBody")
@interface TokenizationBody : P_Body
@property (nonatomic, readonly, strong) TokenizationBodyResponse * _Nullable response;
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK24TokenizationBodyResponse")
@interface TokenizationBodyResponse : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable cardToken;
@property (nonatomic, readonly, copy) NSString * _Nullable ccvToken;
@property (nonatomic, readonly, copy) NSString * _Nullable cardHolderName;
@property (nonatomic, readonly, copy) NSString * _Nullable maskedCard;
@property (nonatomic, readonly, copy) NSString * _Nullable expiryMonth;
@property (nonatomic, readonly, copy) NSString * _Nullable expiryYear;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TokenizationResponse;

SWIFT_CLASS("_TtC17KashierPaymentSDK20TokenizationCallback")
@interface TokenizationCallback : NSObject
@property (nonatomic, copy) void (^ _Nonnull onResponse)(TokenizationResponse * _Nonnull);
- (nonnull instancetype)initOnResponse:(void (^ _Nonnull)(TokenizationResponse * _Nonnull))onResponse onFailure:(void (^ _Nonnull)(ErrorData * _Nonnull))onFailure OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) void (^ _Nonnull onFailure)(ErrorData * _Nonnull);
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK20TokenizationResponse")
@interface TokenizationResponse : GenericResponse
@property (nonatomic, readonly, strong) TokenizationBody * _Nullable tokenizationBody;
@property (nonatomic, readonly, strong) TokenizationBodyResponse * _Nullable cardData;
@end

@class TokensResponse;

SWIFT_CLASS("_TtC17KashierPaymentSDK10TokensList")
@interface TokensList : GenericResponse
@property (nonatomic, readonly, strong) TokensResponse * _Nullable response;
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK18TokensListCallback")
@interface TokensListCallback : NSObject
@property (nonatomic, copy) void (^ _Nonnull onResponse)(TokensList * _Nonnull);
- (nonnull instancetype)initOnResponse:(void (^ _Nonnull)(TokensList * _Nonnull))onResponse onFailure:(void (^ _Nonnull)(ErrorData * _Nonnull))onFailure OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) void (^ _Nonnull onFailure)(ErrorData * _Nonnull);
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK14TokensResponse")
@interface TokensResponse : P_Response
@property (nonatomic, readonly, copy) NSArray<Token *> * _Nullable tokens;
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK11Transaction")
@interface Transaction : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


typedef SWIFT_ENUM(NSInteger, VALIDATION_ERROR, open) {
  VALIDATION_ERRORNO_ERROR = 0,
  VALIDATION_ERRORCARD_HOLDER_NAME_REQUIRED = 1,
  VALIDATION_ERRORCARD_HOLDER_NAME_INVALID = 2,
  VALIDATION_ERRORCVV_REQUIRED = 3,
  VALIDATION_ERRORCVV_INVALID = 4,
  VALIDATION_ERROREXPIRY_DATE_REQUIRED = 5,
  VALIDATION_ERROREXPIRY_DATE_INVALID = 6,
  VALIDATION_ERRORCARD_NUMBER_REQUIRED = 7,
  VALIDATION_ERRORCARD_NUMBER_INVALID = 8,
  VALIDATION_ERRORCARD_NOT_SUPPORTED = 9,
  VALIDATION_ERRORSHOPPER_REFERENCE_REQUIRED = 10,
  VALIDATION_ERRORTOKEN_VALIDITY_REQUIRED = 11,
  VALIDATION_ERRORORDER_ID_REQUIRED = 12,
  VALIDATION_ERRORAMOUNT_REQUIRED = 13,
  VALIDATION_ERRORAMOUNT_INVALID = 14,
  VALIDATION_ERRORCARD_TOKEN_REQUIRED = 15,
  VALIDATION_ERRORCVV_TOKEN_REQUIRED = 16,
  VALIDATION_ERRORSECRET_KEY_REQUIRED = 17,
};

typedef SWIFT_ENUM(NSInteger, VALIDATION_FIELD, open) {
  VALIDATION_FIELDCARD_HOLDER_NAME = 0,
  VALIDATION_FIELDCARD_NUMBER = 1,
  VALIDATION_FIELDCARD_CVV = 2,
  VALIDATION_FIELDCARD_EXPIRY_DATE = 3,
  VALIDATION_FIELDSHOPPER_REFERENCE = 4,
  VALIDATION_FIELDTOKEN_VALIDITY = 5,
  VALIDATION_FIELDORDER_ID = 6,
  VALIDATION_FIELDAMOUNT = 7,
  VALIDATION_FIELDCARD_TOKEN = 8,
  VALIDATION_FIELDCVV_TOKEN = 9,
  VALIDATION_FIELDSECRET_KEY = 10,
};


SWIFT_CLASS("_TtC17KashierPaymentSDK16ValidationResult")
@interface ValidationResult : NSObject
@property (nonatomic, readonly) enum VALIDATION_FIELD validationField;
@property (nonatomic, readonly) BOOL isValid;
@property (nonatomic, readonly, copy) NSString * _Nonnull errorMessage;
@property (nonatomic, readonly) enum VALIDATION_ERROR validationErrorCode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
#ifndef KASHIERPAYMENTSDK_SWIFT_H
#define KASHIERPAYMENTSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="KashierPaymentSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UITextField;
@class NSCoder;
@class NSString;
@class NSBundle;

SWIFT_CLASS("_TtC17KashierPaymentSDK21AddCardViewController")
@interface AddCardViewController : UIViewController <UITextFieldDelegate>
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (void)viewDidLoad;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class ErrorData;

SWIFT_CLASS("_TtC17KashierPaymentSDK4Card")
@interface Card : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull cardHolderName;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardCcv;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardExpiryMonth;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardExpiryYear;
@property (nonatomic, readonly, copy) NSString * _Nonnull cardExpiryDate;
- (nonnull instancetype)initWithCardHolderName:(NSString * _Nonnull)cardHolderName cardNumber:(NSString * _Nonnull)cardNumber cardCcv:(NSString * _Nonnull)cardCcv cardExpiryMonth:(NSString * _Nonnull)cardExpiryMonth cardExpiryYear:(NSString * _Nonnull)cardExpiryYear OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCardHolderName:(NSString * _Nonnull)cardHolderName cardNumber:(NSString * _Nonnull)cardNumber cardCcv:(NSString * _Nonnull)cardCcv cardExpiryDate:(NSString * _Nonnull)cardExpiryDate OBJC_DESIGNATED_INITIALIZER;
+ (ErrorData * _Nonnull)getCardParsingError SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK12Card3DSecure")
@interface Card3DSecure : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable acsURL;
@property (nonatomic, readonly, copy) NSString * _Nullable paReq;
@property (nonatomic, readonly, copy) NSString * _Nullable processACSRedirectURL;
@property (nonatomic, readonly, copy) NSString * _Nullable requestType;
@property (nonatomic, readonly, copy) NSString * _Nullable the3DSecureID;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class CardInfo;
@class Transaction;

SWIFT_CLASS("_TtC17KashierPaymentSDK8CardCard")
@interface CardCard : NSObject
@property (nonatomic, readonly, strong) Card3DSecure * _Nullable the3DSecure;
@property (nonatomic, readonly, strong) CardInfo * _Nullable cardInfo;
@property (nonatomic, readonly, strong) Transaction * _Nullable transaction;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK8CardInfo")
@interface CardInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable cardHolderName;
@property (nonatomic, readonly, copy) NSString * _Nullable expiryMonth;
@property (nonatomic, readonly, copy) NSString * _Nullable expiryYear;
@property (nonatomic, readonly, copy) NSString * _Nullable cardHash;
@property (nonatomic, readonly, copy) NSString * _Nullable cardDataToken;
@property (nonatomic, readonly, copy) NSString * _Nullable cardBrand;
@property (nonatomic, readonly, copy) NSString * _Nullable maskedCard;
@property (nonatomic, readonly, copy) NSString * _Nullable ccvToken;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSNumber;
@class ValidationResult;

SWIFT_CLASS("_TtC17KashierPaymentSDK20CardValidationResult")
@interface CardValidationResult : NSObject
@property (nonatomic, readonly) BOOL isCardValid;
@property (nonatomic, readonly, copy) NSArray<ValidationResult *> * _Nonnull validationErrors;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK23CardsListViewController")
@interface CardsListViewController : UIViewController
- (void)viewDidLoad;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK18Connected_Accounts")
@interface Connected_Accounts : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull mid;
- (nonnull instancetype)initWithMid:(NSString * _Nonnull)mid OBJC_DESIGNATED_INITIALIZER;
- (NSDictionary<NSString *, NSString *> * _Nonnull)toDictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ERROR_TYPE, open) {
  ERROR_TYPENO_VALUE = 0,
  ERROR_TYPEINITIALIZATION = 1,
  ERROR_TYPEVALIDATION = 2,
  ERROR_TYPEDATA = 3,
  ERROR_TYPEEXCEPTION = 4,
  ERROR_TYPENETWORK_ERROR = 5,
  ERROR_TYPENETWORK_NO_INTERNET = 6,
  ERROR_TYPENETWORK_TIMEOUT = 7,
  ERROR_TYPENETWORK_UNAUTHENTICATED = 8,
  ERROR_TYPENETWORK_CLIENT_ERROR = 9,
  ERROR_TYPENETWORK_SERVER_ERROR = 10,
  ERROR_TYPENETWORK_UNEXPECTED_ERROR = 11,
  ERROR_TYPEJSON_PARSING_ERROR = 12,
};

enum KASHIER_RESPONSE_STATUS : NSInteger;
@class GenericResponse;

SWIFT_CLASS("_TtC17KashierPaymentSDK9ErrorData")
@interface ErrorData : NSObject
@property (nonatomic, readonly) enum ERROR_TYPE errorType;
@property (nonatomic, readonly) enum KASHIER_RESPONSE_STATUS responseStatus;
@property (nonatomic, readonly, copy) NSString * _Nonnull errorMessage;
@property (nonatomic, readonly, copy) NSArray<ValidationResult *> * _Nonnull validationErrors;
@property (nonatomic, readonly, strong) GenericResponse * _Nullable Response;
@property (nonatomic, readonly, copy) NSString * _Nonnull exceptionErrorMessage;
@property (nonatomic, readonly, copy) NSString * _Nonnull networkErrorCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)getErrorMessage SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getValidationErrorsMessage SWIFT_WARN_UNUSED_RESULT;
@end

@class P_Body;
@class P_Response;
@class P_Messages;
@class P_Error;

SWIFT_CLASS("_TtC17KashierPaymentSDK15GenericResponse")
@interface GenericResponse : NSObject
@property (nonatomic, strong) P_Body * _Nullable body;
@property (nonatomic, strong) P_Response * _Nullable responseModel;
@property (nonatomic, strong) P_Messages * _Nullable messages;
@property (nonatomic, strong) P_Error * _Nullable error;
@property (nonatomic, copy) NSString * _Nonnull status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, KASHIER_DISPLAY_LANG, open) {
  KASHIER_DISPLAY_LANGAR = 0,
  KASHIER_DISPLAY_LANGEN = 1,
};

typedef SWIFT_ENUM(NSInteger, KASHIER_RESPONSE_STATUS, open) {
  KASHIER_RESPONSE_STATUSNO_VALUE = 0,
  KASHIER_RESPONSE_STATUSUNKNOWN = 1,
  KASHIER_RESPONSE_STATUSSUCCESS = 2,
  KASHIER_RESPONSE_STATUSFAILURE = 3,
  KASHIER_RESPONSE_STATUSINVALID_REQUEST = 4,
  KASHIER_RESPONSE_STATUSPENDING = 5,
  KASHIER_RESPONSE_STATUSPENDING_ACTION = 6,
};

typedef SWIFT_ENUM(NSInteger, KASHIER_SDK_MODE, open) {
  KASHIER_SDK_MODEDEVELOPMENT = 0,
  KASHIER_SDK_MODEPRODUCTION = 1,
};

typedef SWIFT_ENUM(NSInteger, KASHIER_TOKEN_VALIDITY, open) {
  KASHIER_TOKEN_VALIDITYTEMPORARY = 0,
  KASHIER_TOKEN_VALIDITYPERMANENT = 1,
};

@protocol KashierTheme;
@class PaymentCallback;
@class TokensListCallback;
@class TokenizationCallback;
@class OrderDetailsCallback;

SWIFT_CLASS("_TtC17KashierPaymentSDK7Kashier")
@interface Kashier : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) enum KASHIER_SDK_MODE sdkMode;)
+ (enum KASHIER_SDK_MODE)sdkMode SWIFT_WARN_UNUSED_RESULT;
+ (void)setKashierTheme:(id <KashierTheme> _Nonnull)theme;
+ (void)setConnectedAccount:(Connected_Accounts * _Nonnull)connectedAccountData;
+ (void)initializeObjCWithMerchantId:(NSString * _Nonnull)merchantId apiKey:(NSString * _Nonnull)apiKey sdkMode:(enum KASHIER_SDK_MODE)sdkMode;
+ (void)initializeObjCWithMerchantId:(NSString * _Nonnull)merchantId apiKey:(NSString * _Nonnull)apiKey secretKey:(NSString * _Nonnull)secretKey sdkMode:(enum KASHIER_SDK_MODE)sdkMode currency:(NSString * _Nonnull)currency;
+ (void)initializeObjCWithMerchantId:(NSString * _Nonnull)merchantId apiKey:(NSString * _Nonnull)apiKey sdkMode:(enum KASHIER_SDK_MODE)sdkMode secretKey:(NSString * _Nonnull)secretKey currency:(NSString * _Nonnull)currency displayLang:(enum KASHIER_DISPLAY_LANG)displayLang;
+ (void)payWithPermTokenWithShopperReference:(NSString * _Nonnull)shopperReference orderId:(NSString * _Nonnull)orderId amount:(NSString * _Nonnull)amount cardToken:(NSString * _Nonnull)cardToken paymentCallback:(PaymentCallback * _Nonnull)paymentCallback;
+ (void)payWithTempTokenWithShopperReference:(NSString * _Nonnull)shopperReference orderId:(NSString * _Nonnull)orderId amount:(NSString * _Nonnull)amount cardToken:(NSString * _Nonnull)cardToken cvvToken:(NSString * _Nonnull)cvvToken paymentCallback:(PaymentCallback * _Nonnull)paymentCallback;
+ (void)payWithCardWithCardData:(Card * _Nonnull)cardData orderId:(NSString * _Nonnull)orderId amount:(NSString * _Nonnull)amount shopperReference:(NSString * _Nonnull)shopperReference shouldSaveCard:(BOOL)shouldSaveCard paymentCallback:(PaymentCallback * _Nonnull)paymentCallback;
+ (void)listShopperCardsWithShopperReference:(NSString * _Nonnull)shopperReference userCallBack:(TokensListCallback * _Nonnull)userCallBack;
+ (void)saveShopperCardWithCardData:(Card * _Nonnull)cardData shopperReference:(NSString * _Nonnull)shopperReference tokenValidity:(enum KASHIER_TOKEN_VALIDITY)tokenValidity tokenizationCallback:(TokenizationCallback * _Nonnull)tokenizationCallback;
+ (void)payUsingPaymentFormWithOrderId:(NSString * _Nonnull)orderId amount:(NSString * _Nonnull)amount shopperReference:(NSString * _Nonnull)shopperReference paymentCallback:(PaymentCallback * _Nonnull)paymentCallback customXibFile:(NSString * _Nullable)customXibFile;
+ (void)listShopperCardsUIWithShopperReference:(NSString * _Nonnull)shopperReference;
+ (void)getOrderDetailsWithOrderId:(NSString * _Nonnull)orderId shopperReference:(NSString * _Nullable)shopperReference orderDetailsCallback:(OrderDetailsCallback * _Nonnull)orderDetailsCallback;
+ (NSString * _Nonnull)getString SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getStringWithParamWithStr:(NSString * _Nonnull)myStr SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;

SWIFT_PROTOCOL("_TtP17KashierPaymentSDK12KashierTheme_")
@protocol KashierTheme
@property (nonatomic, strong) UIColor * _Nonnull primaryColor;
@property (nonatomic, strong) UIColor * _Nonnull primaryColorVariant;
@property (nonatomic, strong) UIColor * _Nonnull secondaryColor;
/// Can be used to extend the functionality of the theme, by applying more colors to some components
- (void)extend;
@end

@class UIApplication;

SWIFT_CLASS("_TtC17KashierPaymentSDK18KashierThemeHelper")
@interface KashierThemeHelper : NSObject
+ (void)applyThemeFor:(UIApplication * _Nonnull)application kashierTheme:(id <KashierTheme> _Nonnull)kashierTheme;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK19KashierThemedButton")
@interface KashierThemedButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK18KashierUITextField")
@interface KashierUITextField : UITextField
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC17KashierPaymentSDK8Merchant")
@interface Merchant : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable merchantRedirectURL;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC17KashierPaymentSDK5Order")
@interface Order : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class OrderDetailsResponse;

SWIFT_CLASS("_TtC17KashierPaymentSDK12OrderDetails")
@interface OrderDetails : GenericResponse
@property (nonatomic, readonly, strong) OrderDetailsResponse * _Nullable orderDetailsResponse;
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK20OrderDetailsCallback")
@interface OrderDetailsCallback : NSObject
@property (nonatomic, copy) void (^ _Nonnull onResponse)(OrderDetails * _Nonnull);
- (nonnull instancetype)initOnResponse:(void (^ _Nonnull)(OrderDetails * _Nonnull))onResponse onFailure:(void (^ _Nonnull)(ErrorData * _Nonnull))onFailure OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) void (^ _Nonnull onFailure)(ErrorData * _Nonnull);
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class P_Message;
@class P_Card;

SWIFT_CLASS("_TtC17KashierPaymentSDK10P_Response")
@interface P_Response : NSObject
@property (nonatomic, readonly, strong) P_Messages * _Nullable messages;
@property (nonatomic, readonly, copy) NSString * _Nullable status;
@property (nonatomic, readonly, strong) P_Message * _Nullable message;
@property (nonatomic, readonly, strong) P_Card * _Nullable cardModel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class OrderDetailsSourceOfFunds;
@class OrderDetails_merchantDetails;
@class OrderDetails_order;
@class OrderDetails_transaction;

SWIFT_CLASS("_TtC17KashierPaymentSDK20OrderDetailsResponse")
@interface OrderDetailsResponse : P_Response
@property (nonatomic, readonly, copy) NSString * _Nullable _id;
@property (nonatomic, readonly, copy) NSString * _Nullable merchantId;
@property (nonatomic, readonly, copy) NSString * _Nullable orderId;
@property (nonatomic, readonly, copy) NSString * _Nullable merchantOrderId;
@property (nonatomic, readonly, copy) NSString * _Nullable totalAuthorizedAmount;
@property (nonatomic, readonly, copy) NSString * _Nullable method;
@property (nonatomic, readonly, copy) NSString * _Nullable apiKeyId;
@property (nonatomic, readonly, copy) NSString * _Nullable apiServiceName;
@property (nonatomic, readonly, copy) NSString * _Nullable paymentOrigin;
@property (nonatomic, readonly, copy) NSString * _Nullable paymentChannel;
@property (nonatomic, readonly, copy) NSString * _Nullable provider;
@property (nonatomic, readonly, copy) NSString * _Nullable lastModifiedDate;
@property (nonatomic, readonly, copy) NSString * _Nullable date;
@property (nonatomic, readonly, strong) OrderDetailsSourceOfFunds * _Nullable sourceOfFunds;
@property (nonatomic, readonly, strong) OrderDetails_merchantDetails * _Nullable merchantDetails;
@property (nonatomic, readonly, strong) OrderDetails_order * _Nullable order;
@property (nonatomic, readonly, copy) NSArray<OrderDetails_transaction *> * _Nullable transactions;
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK25OrderDetailsSourceOfFunds")
@interface OrderDetailsSourceOfFunds : NSObject
@property (nonatomic, readonly, strong) CardInfo * _Nullable cardInfo;
@property (nonatomic, readonly, strong) Card3DSecure * _Nullable threeDSecure;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK28OrderDetails_merchantDetails")
@interface OrderDetails_merchantDetails : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable storeName;
@property (nonatomic, readonly, copy) NSString * _Nullable merchantId;
@property (nonatomic, readonly, copy) NSString * _Nullable businessIndustry;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK18OrderDetails_order")
@interface OrderDetails_order : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable amount;
@property (nonatomic, readonly, copy) NSString * _Nullable currency;
@property (nonatomic, readonly, copy) NSString * _Nullable callbackURL;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK24OrderDetails_transaction")
@interface OrderDetails_transaction : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable currency;
@property (nonatomic, readonly, copy) NSString * _Nullable status;
@property (nonatomic, readonly, copy) NSString * _Nullable transactionId;
@property (nonatomic, readonly, copy) NSString * _Nullable operation;
@property (nonatomic, readonly, copy) NSString * _Nullable _id;
@property (nonatomic, readonly, copy) NSString * _Nullable requestDate;
@property (nonatomic, readonly, copy) NSString * _Nullable responseDate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK6P_Body")
@interface P_Body : NSObject
@property (nonatomic, readonly, strong) P_Messages * _Nullable messages;
@property (nonatomic, readonly, copy) NSString * _Nullable status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK6P_Card")
@interface P_Card : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable result;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK7P_Error")
@interface P_Error : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable cause;
@property (nonatomic, readonly, copy) NSString * _Nullable explanation;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK9P_Message")
@interface P_Message : NSObject
@property (nonatomic, readonly, strong) P_Messages * _Nullable messages;
@property (nonatomic, readonly, copy) NSString * _Nullable status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK10P_Messages")
@interface P_Messages : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable en;
@property (nonatomic, readonly, copy) NSString * _Nullable ar;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK10P_Platform")
@interface P_Platform : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable mid;
@property (nonatomic, readonly, copy) NSString * _Nullable storeName;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



IB_DESIGNABLE
SWIFT_CLASS("_TtC17KashierPaymentSDK12PaddingLabel")
@interface PaddingLabel : UILabel
- (void)drawTextInRect:(CGRect)rect;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class PaymentResponse;

SWIFT_CLASS("_TtC17KashierPaymentSDK7Payment")
@interface Payment : GenericResponse
@property (nonatomic, readonly, strong) PaymentResponse * _Nullable response;
- (Card3DSecure * _Nullable)get3DSData SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK15PaymentCallback")
@interface PaymentCallback : NSObject
@property (nonatomic, copy) void (^ _Nonnull onResponse)(Payment * _Nonnull);
- (nonnull instancetype)initOnResponse:(void (^ _Nonnull)(Payment * _Nonnull))onResponse onFailure:(void (^ _Nonnull)(ErrorData * _Nonnull))onFailure OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) void (^ _Nonnull onFailure)(ErrorData * _Nonnull);
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK25PaymentFormViewController")
@interface PaymentFormViewController : UIViewController
- (void)viewDidLoad;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class ResponseCard;
@class SourceOfFunds;

SWIFT_CLASS("_TtC17KashierPaymentSDK15PaymentResponse")
@interface PaymentResponse : P_Response
@property (nonatomic, readonly, copy) NSString * _Nullable orderReference;
@property (nonatomic, readonly, copy) NSString * _Nullable orderID;
@property (nonatomic, readonly, copy) NSString * _Nullable transactionID;
@property (nonatomic, readonly, copy) NSString * _Nullable merchantOrderID;
@property (nonatomic, readonly, copy) NSString * _Nullable creationDate;
@property (nonatomic, readonly, copy) NSString * _Nullable providerType;
@property (nonatomic, readonly, copy) NSString * _Nullable method;
@property (nonatomic, readonly, copy) NSString * _Nullable apiKeyID;
@property (nonatomic, readonly, copy) NSString * _Nullable refID;
@property (nonatomic, readonly, copy) NSString * _Nullable merchantID;
@property (nonatomic, readonly, strong) ResponseCard * _Nullable card;
@property (nonatomic, readonly, strong) SourceOfFunds * _Nullable sourceOfFunds;
@property (nonatomic, readonly, strong) P_Error * _Nullable error;
@property (nonatomic, readonly, strong) P_Platform * _Nullable platform;
@end

@class ProvidedCard;

SWIFT_CLASS("_TtC17KashierPaymentSDK8Provided")
@interface Provided : NSObject
@property (nonatomic, readonly, strong) ProvidedCard * _Nullable card;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK12ProvidedCard")
@interface ProvidedCard : NSObject
@property (nonatomic, readonly, strong) CardCard * _Nullable card;
@property (nonatomic, readonly, strong) CardInfo * _Nullable cardInfo;
@property (nonatomic, readonly, strong) Card3DSecure * _Nullable the3DSecure;
@property (nonatomic, readonly, strong) Transaction * _Nullable transaction;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK8Response")
@interface Response : NSObject
@property (nonatomic, readonly, strong) SourceOfFunds * _Nullable sourceOfFunds;
@property (nonatomic, readonly, copy) NSString * _Nullable orderReference;
@property (nonatomic, readonly, copy) NSString * _Nullable orderID;
@property (nonatomic, readonly, copy) NSString * _Nullable transactionID;
@property (nonatomic, readonly, copy) NSString * _Nullable merchantOrderID;
@property (nonatomic, readonly, copy) NSString * _Nullable creationDate;
@property (nonatomic, readonly, copy) NSString * _Nullable providerType;
@property (nonatomic, readonly, copy) NSString * _Nullable method;
@property (nonatomic, readonly, copy) NSString * _Nullable apiKeyID;
@property (nonatomic, readonly, copy) NSString * _Nullable refID;
@property (nonatomic, readonly, copy) NSString * _Nullable merchantID;
@property (nonatomic, readonly, strong) ResponseCard * _Nullable card;
@property (nonatomic, readonly, strong) P_Platform * _Nullable platform;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK12ResponseCard")
@interface ResponseCard : NSObject
@property (nonatomic, readonly, strong) CardInfo * _Nullable cardInfo;
@property (nonatomic, readonly, strong) Order * _Nullable order;
@property (nonatomic, readonly) double amount;
@property (nonatomic, readonly, copy) NSString * _Nullable currency;
@property (nonatomic, readonly, copy) NSString * _Nullable result;
@property (nonatomic, readonly, strong) Merchant * _Nullable merchant;
@property (nonatomic, readonly, strong) Card3DSecure * _Nullable card3DSecure;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK13SourceOfFunds")
@interface SourceOfFunds : NSObject
@property (nonatomic, readonly, strong) Provided * _Nullable provided;
@property (nonatomic, readonly, copy) NSString * _Nullable type;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIImage;

SWIFT_CLASS("_TtC17KashierPaymentSDK5Token")
@interface Token : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable cardExpiryYear;
@property (nonatomic, readonly, copy) NSString * _Nullable cardExpiryMonth;
@property (nonatomic, readonly, copy) NSString * _Nullable cardNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable creationDate;
@property (nonatomic, readonly, copy) NSString * _Nullable token;
@property (nonatomic, readonly, copy) NSString * _Nullable shopperReference;
@property (nonatomic, readonly, copy) NSString * _Nullable merchantID;
@property (nonatomic, readonly, copy) NSString * _Nullable cardType;
@property (nonatomic, readonly, strong) UIImage * _Nullable cardImage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TokenizationBodyResponse;

SWIFT_CLASS("_TtC17KashierPaymentSDK16TokenizationBody")
@interface TokenizationBody : P_Body
@property (nonatomic, readonly, strong) TokenizationBodyResponse * _Nullable response;
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK24TokenizationBodyResponse")
@interface TokenizationBodyResponse : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable cardToken;
@property (nonatomic, readonly, copy) NSString * _Nullable ccvToken;
@property (nonatomic, readonly, copy) NSString * _Nullable cardHolderName;
@property (nonatomic, readonly, copy) NSString * _Nullable maskedCard;
@property (nonatomic, readonly, copy) NSString * _Nullable expiryMonth;
@property (nonatomic, readonly, copy) NSString * _Nullable expiryYear;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TokenizationResponse;

SWIFT_CLASS("_TtC17KashierPaymentSDK20TokenizationCallback")
@interface TokenizationCallback : NSObject
@property (nonatomic, copy) void (^ _Nonnull onResponse)(TokenizationResponse * _Nonnull);
- (nonnull instancetype)initOnResponse:(void (^ _Nonnull)(TokenizationResponse * _Nonnull))onResponse onFailure:(void (^ _Nonnull)(ErrorData * _Nonnull))onFailure OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) void (^ _Nonnull onFailure)(ErrorData * _Nonnull);
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK20TokenizationResponse")
@interface TokenizationResponse : GenericResponse
@property (nonatomic, readonly, strong) TokenizationBody * _Nullable tokenizationBody;
@property (nonatomic, readonly, strong) TokenizationBodyResponse * _Nullable cardData;
@end

@class TokensResponse;

SWIFT_CLASS("_TtC17KashierPaymentSDK10TokensList")
@interface TokensList : GenericResponse
@property (nonatomic, readonly, strong) TokensResponse * _Nullable response;
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK18TokensListCallback")
@interface TokensListCallback : NSObject
@property (nonatomic, copy) void (^ _Nonnull onResponse)(TokensList * _Nonnull);
- (nonnull instancetype)initOnResponse:(void (^ _Nonnull)(TokensList * _Nonnull))onResponse onFailure:(void (^ _Nonnull)(ErrorData * _Nonnull))onFailure OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) void (^ _Nonnull onFailure)(ErrorData * _Nonnull);
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK14TokensResponse")
@interface TokensResponse : P_Response
@property (nonatomic, readonly, copy) NSArray<Token *> * _Nullable tokens;
@end


SWIFT_CLASS("_TtC17KashierPaymentSDK11Transaction")
@interface Transaction : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


typedef SWIFT_ENUM(NSInteger, VALIDATION_ERROR, open) {
  VALIDATION_ERRORNO_ERROR = 0,
  VALIDATION_ERRORCARD_HOLDER_NAME_REQUIRED = 1,
  VALIDATION_ERRORCARD_HOLDER_NAME_INVALID = 2,
  VALIDATION_ERRORCVV_REQUIRED = 3,
  VALIDATION_ERRORCVV_INVALID = 4,
  VALIDATION_ERROREXPIRY_DATE_REQUIRED = 5,
  VALIDATION_ERROREXPIRY_DATE_INVALID = 6,
  VALIDATION_ERRORCARD_NUMBER_REQUIRED = 7,
  VALIDATION_ERRORCARD_NUMBER_INVALID = 8,
  VALIDATION_ERRORCARD_NOT_SUPPORTED = 9,
  VALIDATION_ERRORSHOPPER_REFERENCE_REQUIRED = 10,
  VALIDATION_ERRORTOKEN_VALIDITY_REQUIRED = 11,
  VALIDATION_ERRORORDER_ID_REQUIRED = 12,
  VALIDATION_ERRORAMOUNT_REQUIRED = 13,
  VALIDATION_ERRORAMOUNT_INVALID = 14,
  VALIDATION_ERRORCARD_TOKEN_REQUIRED = 15,
  VALIDATION_ERRORCVV_TOKEN_REQUIRED = 16,
  VALIDATION_ERRORSECRET_KEY_REQUIRED = 17,
};

typedef SWIFT_ENUM(NSInteger, VALIDATION_FIELD, open) {
  VALIDATION_FIELDCARD_HOLDER_NAME = 0,
  VALIDATION_FIELDCARD_NUMBER = 1,
  VALIDATION_FIELDCARD_CVV = 2,
  VALIDATION_FIELDCARD_EXPIRY_DATE = 3,
  VALIDATION_FIELDSHOPPER_REFERENCE = 4,
  VALIDATION_FIELDTOKEN_VALIDITY = 5,
  VALIDATION_FIELDORDER_ID = 6,
  VALIDATION_FIELDAMOUNT = 7,
  VALIDATION_FIELDCARD_TOKEN = 8,
  VALIDATION_FIELDCVV_TOKEN = 9,
  VALIDATION_FIELDSECRET_KEY = 10,
};


SWIFT_CLASS("_TtC17KashierPaymentSDK16ValidationResult")
@interface ValidationResult : NSObject
@property (nonatomic, readonly) enum VALIDATION_FIELD validationField;
@property (nonatomic, readonly) BOOL isValid;
@property (nonatomic, readonly, copy) NSString * _Nonnull errorMessage;
@property (nonatomic, readonly) enum VALIDATION_ERROR validationErrorCode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
